---
# tasks file for create-elb
- name: Create load balancer
  ec2_elb_lb:
    cross_az_load_balancing : "{{ elb.cross_az_load_balancing | default('no') }}"
    health_check            : "{{ elb.health_check | default([]) }}"
    idle_timeout            : "{{ elb.idle_timeout | default('') }}"
    listeners               : "{{ elb.listeners | default([]) }}"
    subnets                 : "{{ elb.subnets | default([]) }}"
    zones                   : "{{ elb.zones | default([]) }}"
    name                    : "{{ elb.name }}"
    region                  : "{{ elb.region }}"
    scheme                  : "{{ elb.scheme | default('internal-facing') }}"
    security_group_ids      : "{{ elb.security_group_ids }}"
    state                   : present
    

